name: school-report
app_id: da_R4qIGtmUDz3J
owner: src48
package: .
locality:
  regions:
  - fr-roub1
capabilities:
  database:
    engine: mysql
scaling:
  mode: single_concurrency
kind: wasmer.io/App.v0
description: School Result Management System
